#!/bin/bash
set -euo pipefail

# Build cr-daemon (release) and assemble it into an ad-hoc-signed .app bundle.
# SwiftPM emits a bare binary; this wraps it with Info.plist (LSUIElement) so it
# runs as a menu-bar-only app. No full Xcode required.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_NAME="cr-daemon"
BUILD_DIR="$ROOT/build"
BUNDLE="$BUILD_DIR/${APP_NAME}.app"
BUILD_INFO="$ROOT/Sources/CRDaemonCore/BuildInfo.swift"

# Inject the build provenance (short SHA + date) so the installed app reports the
# exact commit it was built from. The committed BuildInfo.swift carries a "dev"
# default for plain `swift build`; we overwrite it here and restore it after.
inject_build_info() {
    local sha date
    sha="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    date="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    cat > "$BUILD_INFO" <<EOF
import Foundation

// Generated by Scripts/make-app.sh at build time — do not edit by hand.
// The committed default (gitSHA = "dev") is restored after the build.
public enum BuildInfo {
    public static let gitSHA = "$sha"
    public static let date = "$date"
}
EOF
}

restore_build_info() {
    git -C "$ROOT" checkout -- "$BUILD_INFO" 2>/dev/null || true
}

echo "==> injecting build info"
inject_build_info
trap restore_build_info EXIT

echo "==> swift build -c release"
swift build -c release --package-path "$ROOT"
BIN_DIR="$(swift build -c release --package-path "$ROOT" --show-bin-path)"

echo "==> assembling ${APP_NAME}.app"
rm -rf "$BUNDLE"
mkdir -p "$BUNDLE/Contents/MacOS" "$BUNDLE/Contents/Resources"
cp "$BIN_DIR/$APP_NAME" "$BUNDLE/Contents/MacOS/$APP_NAME"
cp "$ROOT/Resources/Info.plist" "$BUNDLE/Contents/Info.plist"

# Ad-hoc signature (required on Apple Silicon to run). Not notarized — this is a
# local, single-user build. See README "Signing & Gatekeeper".
echo "==> ad-hoc codesign"
codesign --force --sign - "$BUNDLE"

echo "built: $BUNDLE"
